version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  alertmanager-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 9999:9090
    volumes:
      - prometheus-data:/etc/prometheus
      - /etc/prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager

    ports:
      - 9093:9093
    volumes:
      - alertmanager-data:/etc/alertmanager
      - /etc/alertmanager:/etc/alertmanager
    command: --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug
    restart: unless-stopped
