global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
#   scrape_timeout: 90s
    static_configs:
    - targets: ['192.168.35.1:8002']

rule_files:
  - 'alert-rules.yml'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
